function add_decomps(obj, decomp_obj)
	empty_stat = obj.sfill([], []);

	% Decomposition wrt no inc risk model
	empty_decomp_struct = struct(...
		'htm_level', empty_stat,...
		'term1', empty_stat, 'term1_pct', empty_stat,...
		'term2', empty_stat, 'term3', empty_stat,...
		'term4', empty_stat...
	);
	n = numel(obj.p.decomp_thresholds);

	norisk = decomp_obj.results_norisk;
	obj.decomp_norisk = empty_decomp_struct;
	obj.decomp_norisk_completed = norisk.completed;
	for it = 1:n
		lvl = obj.p.decomp_thresholds(it);

		obj.decomp_norisk(it) = empty_decomp_struct;
		obj.decomp_norisk(it).htm_level = obj.sfill(...
			lvl, 'HtM threshold');

		obj.decomp_norisk(it).term1 = obj.sfill(...
			norisk.term1(it), 'RA MPC');

		obj.decomp_norisk(it).term1_pct = obj.sfill(...
			norisk.term1(it) * 100, 'RA MPC (%)');

		tmp = sprintf('HtM effect (abar <= %g)', lvl);
		obj.decomp_norisk(it).term2 = obj.sfill(...
			norisk.term2(it), tmp);

		tmp = sprintf(...
			'Non-HtM (abar > %g), constraint effect ', lvl);
		obj.decomp_norisk(it).term3 = obj.sfill(...
			norisk.term3(it), tmp);

		tmp = sprintf(...
			'Non-HtM (abar > %g), inc risk effect ', lvl);
		obj.decomp_norisk(it).term4 = obj.sfill(...
			norisk.term4(it), tmp);
	end

	% Decomposition wrt RA model
	n = numel(obj.p.decomp_thresholds);

	results_RA = decomp_obj.results_RA;
	obj.decomp_RA = struct();
	obj.decomp_RA.mpc_RA = obj.sfill(decomp_obj.m_ra,...
		'MPC of RA model');
	obj.decomp_RA.mean_mpc_diff = obj.sfill(...
		results_RA.Em1_less_mRA,...
		'E[MPC] - MPC_ra');
	obj.decomp_RA.term1 = obj.sfill(...
		results_RA.term1,...
		'Effect of MPC fcn');
	obj.decomp_RA.term2 = obj.sfill(...
		results_RA.term2,...
		'Effect of distribution');
	obj.decomp_RA.term3 = obj.sfill(...
		results_RA.term3,...
		'Interaction');
end