function stats = add_comparison_decomps(p, stats, decomp_bl)
	% Decomposition wrt no inc risk model
	stats.decomp_baseline = struct();

	mDiff = decomp_bl.Em1_less_Em0;
	stats.decomp_baseline.mean_mpc_diff = sfill(...
		mDiff, 'E[MPC] - E[MPC_b]');

	if abs(mDiff) < 1e-6
		mDiff = NaN;
	end

	to_pct = @(z) 100 * z / mDiff;

	stats.decomp_baseline.term1 = sfill(...
		decomp_bl.term1,...
		'Effect of mpc fcn');
	stats.decomp_baseline.term1_pct = sfill(...
		to_pct(decomp_bl.term1),...
		'Effect of mpc fcn (%)');

	stats.decomp_baseline.term2 = sfill(...
		decomp_bl.term2,...
		'Effect of distribution');
	stats.decomp_baseline.term2_pct = sfill(...
		to_pct(decomp_bl.term2),...
		'Effect of distribution (%)');

	stats.decomp_baseline.term3 = sfill(...
		decomp_bl.term3,...
		'Interaction');
	stats.decomp_baseline.term3_pct = sfill(...
		to_pct(decomp_bl.term3),...
		'Interaction (%)');

	for ia = 1:numel(p.decomp_thresholds)
        x = p.decomp_thresholds(ia);

        if p.OneAsset
        	stats.decomp_baseline.term2a(ia) = sfill(...
				decomp_bl.term2a(ia),...
				sprintf('Distr effect, HtM (eps = %g)', x));
			stats.decomp_baseline.term2b(ia) = sfill(...
				decomp_bl.term2b(ia),...
				sprintf('Distr effect, NHtM (eps = %g)', x));
			stats.decomp_baseline.term2c(ia) = sfill(...
				NaN, 'N/A', 2);

			stats.decomp_baseline.term2a_pct(ia) = sfill(...
				to_pct(decomp_bl.term2a(ia)),...
				sprintf('Distr effect (%%), HtM (eps = %g)', x));
			stats.decomp_baseline.term2b_pct(ia) = sfill(...
				to_pct(decomp_bl.term2b(ia)),...
				sprintf('Distr effect (%%), NHtM (eps = %g)', x));
			stats.decomp_baseline.term2c_pct(ia) = sfill(...
				NaN, 'N/A', 2);
        else
			stats.decomp_baseline.term2a(ia) = sfill(...
				decomp_bl.term2a(ia),...
				sprintf('Distr effect, PHtM (eps = %g)', x));
			stats.decomp_baseline.term2b(ia) = sfill(...
				decomp_bl.term2b(ia),...
				sprintf('Distr effect, WHtM (eps = %g)', x));
			stats.decomp_baseline.term2c(ia) = sfill(...
				decomp_bl.term2c(ia),...
				sprintf('Distr effect, NHtM (eps = %g)', x), 2);

			stats.decomp_baseline.term2a_pct(ia) = sfill(...
				to_pct(decomp_bl.term2a(ia)),...
				sprintf('Distr effect (%%), PHtM (eps = %g)', x));
			stats.decomp_baseline.term2b_pct(ia) = sfill(...
				to_pct(decomp_bl.term2b(ia)),...
				sprintf('Distr effect (%%), WHtM (eps = %g)', x));
			stats.decomp_baseline.term2c_pct(ia) = sfill(...
				to_pct(decomp_bl.term2c(ia)),...
				sprintf('Distr effect (%%), NHtM (eps = %g)', x), 2);
		end
	end

	stats.decomp_baseline_present = true;
end

function out = sfill(value, label, asset_indicator)
	% 0 - both assets
	% 1 asset only
	% 2 asset only

	if nargin < 3
		asset_indicator = 0;
	end

	out = struct(...
		'value', value,...
		'label', label,...
		'indicator', asset_indicator...
	);
end
